version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "docker"
    directory: "livebook/"
    schedule:
      interval: "weekly"
      day: "friday"
