version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "lidarr/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "radarr/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "sonarr/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "sabnzbd/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "livebook/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "eufy-security/"
    schedule:
      interval: "weekly"
