name: build and update

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
env:
  ARCH_PLATFORMS: '{"amd64":"linux/amd64","aarch64":"linux/arm64","armhf":"linux/arm/v7"}'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [ sabnzbd, sonarr, radarr, lidarr ]
    env:
      CONFIG_FILE: "${{ matrix.addon }}/config.json"
      DOCKERFILE: "${{ matrix.addon }}/Dockerfile"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - id: config
        name: Extract config version
        run: |
          jq -r '"version=\(.version)"' "$CONFIG_FILE" >> "$GITHUB_OUTPUT"
          jq -r '"image=\(.image)"' "$CONFIG_FILE" >> "$GITHUB_OUTPUT"
          jq --argjson archs "$ARCH_PLATFORMS" -r '.arch | map($archs[.]) | map(select(.)) | join(",") | "platforms=\(.)"' "$CONFIG_FILE" >> "$GITHUB_OUTPUT"

      - id: image
        name: Fetch image version
        run: |
          from=$(awk '{if ($1 == "FROM") {print $2}}' "$DOCKERFILE")
          image_tag=${from#*/}
          image=${image_tag%:*}
          digest=latest
          media_type='application/vnd.docker.distribution.manifest.list.v2+json'
          token=$(curl -sG --data-urlencode "scope=repository:${image}:pull" \
            'https://ghcr.io/token' \
            | jq -r '.token')
          while [[ "$media_type" == 'application/vnd.docker.distribution.manifest.list.v2+json' ]]; do
            response=$(curl -s \
              --header 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
              --header "Authorization: Bearer ${token}" \
              "https://ghcr.io/v2/${image}/manifests/${digest}")
            media_type=$(echo $response | jq -r .mediaType)
            digest=$(echo $response | jq -r '.manifests | first | .digest')
          done
          digest=$(echo $response | jq -r .config.digest)
          ext_version=$(curl -sL \
            --header "Authorization: Bearer ${token}" \
            "https://ghcr.io/v2/${image}/blobs/${digest}" \
            | jq -r '.container_config // .config | .Labels["org.opencontainers.image.version"]')
          echo "version=${ext_version}" >> "$GITHUB_OUTPUT"
          if [[ "$version" == "$image_tag" && "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            echo "skip_version=1" >> "$GITHUB_OUTPUT"
          else
            echo "skip_version=" >> "$GITHUB_OUTPUT"
          fi

      - name: Update files
        if: ${{ !steps.image.outputs.skip_version }}
        env:
          IMAGE_VERSION: ${{ steps.image.outputs.version }}
        run: |
          jq --arg version "$IMAGE_VERSION" '. + {version: $version}' "$CONFIG_FILE" > "${CONFIG_FILE}.new"
          sed -i -e "s/:.*/:${IMAGE_VERSION}/" "$DOCKERFILE"
          mv -f "${CONFIG_FILE}.new" "$CONFIG_FILE"

      - name: Set up QEMU
        if: ${{ !steps.image.outputs.skip_version }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: ${{ !steps.image.outputs.skip_version }}
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: ${{ !steps.image.outputs.skip_version }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        if: ${{ !steps.image.outputs.skip_version }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        if: ${{ !steps.image.outputs.skip_version }}
        run: docker build -t ${{ matrix.addon }}:${{ github.sha }} ${{ matrix.addon }}

      - name: Test container
        if: ${{ !steps.image.outputs.skip_version }}
        uses: plexsystems/container-structure-test-action@v0.3.0
        with:
          image: ${{ matrix.addon }}:${{ github.sha }}
          config: ${{ matrix.addon }}/test.yaml

      - name: Push container
        if: ${{ !steps.image.outputs.skip_version }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.addon }}
          platforms: ${{ steps.config.outputs.platforms }}
          push: true
          tags: |
            ${{ steps.config.outputs.image }}:${{ steps.image.outputs.version }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Commit changes
        run: |
          git ls-files --modified --error-unmatch "$CONFIG_FILE" || exit 0
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "$CONFIG_FILE"
          git commit -m "Version bump ${{ matrix.addon }} to ${{ steps.image.outputs.version }}"
          git pull --rebase --quiet
          git push --quiet
          test -z "<($GITHUB_STEP_SUMMARY)" && echo "# Update summary" >> "$GITHUB_STEP_SUMMARY"
          echo "* **${{ matrix.addon }}** updated to version ${{ steps.image.outputs.version }}" >> "$GITHUB_STEP_SUMMARY"
