name: Build pull request
on:
  pull_request:
    paths:
      - '*/Dockerfile'
      - '*/rootfs/**'
    types:
      - closed

jobs:
  inspect:
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.addons.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: addons
        with:
          script: |
            const { commits } = context.payload
            const changedFiles = [
              ...commits.added,
              ...commits.modified,
              ...commits.removed,
            ]
            let patterns = []
            changedFiles.forEach(changedFile => {
              const changedFolder = changedFile.split('/')[0]
              const pattern = `${changedFolder}/Dockerfile`
              if (!patterns.includes(pattern)) {
                patterns.push(pattern)
              }
            })
            const globber = await glob.create(patterns.join('\n'))
            const files = await globber.glob()
            return files.map(file => file.split('/')[0])

  build:
    needs: inspect
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: ${{ needs.inspect.outputs.addons }}
    uses: ./.github/workflows/build.yml
    with:
      addon: ${{ matrix.addon }}
      publish: ${{ github.event.pull_request.merged == true }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
